// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransformerAI.Maintenance.Api.Data;

#nullable disable

namespace TransformerAI.Maintenance.Api.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260910132941_SiraNumarasiVeGecisKurallari")]
    partial class SiraNumarasiVeGecisKurallari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Technician", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxOpenOrders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("technicians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TK-01",
                            IsActive = true,
                            MaxOpenOrders = 3,
                            Name = "Ahmet Yılmaz",
                            Region = "Marmara",
                            Specialty = "Electrical"
                        },
                        new
                        {
                            Id = "TK-02",
                            IsActive = true,
                            MaxOpenOrders = 3,
                            Name = "Elif Demir",
                            Region = "Marmara",
                            Specialty = "Thermal"
                        },
                        new
                        {
                            Id = "TK-03",
                            IsActive = true,
                            MaxOpenOrders = 5,
                            Name = "Mehmet Kaya",
                            Region = "Marmara",
                            Specialty = "Sampling"
                        },
                        new
                        {
                            Id = "TK-04",
                            IsActive = true,
                            MaxOpenOrders = 4,
                            Name = "Zeynep Şahin",
                            Region = "Ege",
                            Specialty = "General"
                        },
                        new
                        {
                            Id = "TK-05",
                            IsActive = true,
                            MaxOpenOrders = 4,
                            Name = "Burak Aydın",
                            Region = "İç Anadolu",
                            Specialty = "General"
                        },
                        new
                        {
                            Id = "TK-06",
                            IsActive = true,
                            MaxOpenOrders = 4,
                            Name = "Selin Öztürk",
                            Region = "Akdeniz",
                            Specialty = "Sampling"
                        });
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.WorkOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Priority")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TransformerId");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("TransformerAI.Maintenance.Api.Models.Technician", "Technician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
