// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransformerAI.Maintenance.Api.Data;

#nullable disable

namespace TransformerAI.Maintenance.Api.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260911111955_Bildirimler")]
    partial class Bildirimler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<double>("Priority")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientEmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("RecipientId", "Status");

                    b.HasIndex("WorkOrderId", "RecipientId", "Trigger")
                        .IsUnique();

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Session", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicianId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TechnicianId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Technician", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxOpenOrders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PinSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNo")
                        .IsUnique();

                    b.ToTable("technicians", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "TK-01",
                            EmployeeNo = "10247",
                            FailedAttempts = 0,
                            IsActive = true,
                            MaxOpenOrders = 3,
                            Name = "Ahmet Yılmaz",
                            PinHash = "",
                            PinSalt = "",
                            Region = "Marmara",
                            Role = "Technician",
                            Specialty = "Electrical"
                        },
                        new
                        {
                            Id = "TK-02",
                            EmployeeNo = "10318",
                            FailedAttempts = 0,
                            IsActive = true,
                            MaxOpenOrders = 3,
                            Name = "Elif Demir",
                            PinHash = "",
                            PinSalt = "",
                            Region = "Marmara",
                            Role = "Engineer",
                            Specialty = "Thermal"
                        },
                        new
                        {
                            Id = "TK-03",
                            EmployeeNo = "10455",
                            FailedAttempts = 0,
                            IsActive = true,
                            MaxOpenOrders = 5,
                            Name = "Mehmet Kaya",
                            PinHash = "",
                            PinSalt = "",
                            Region = "Marmara",
                            Role = "Technician",
                            Specialty = "Sampling"
                        },
                        new
                        {
                            Id = "TK-04",
                            EmployeeNo = "10502",
                            FailedAttempts = 0,
                            IsActive = true,
                            MaxOpenOrders = 4,
                            Name = "Zeynep Şahin",
                            PinHash = "",
                            PinSalt = "",
                            Region = "Ege",
                            Role = "Supervisor",
                            Specialty = "General"
                        },
                        new
                        {
                            Id = "TK-05",
                            EmployeeNo = "10611",
                            FailedAttempts = 0,
                            IsActive = true,
                            MaxOpenOrders = 4,
                            Name = "Burak Aydın",
                            PinHash = "",
                            PinSalt = "",
                            Region = "İç Anadolu",
                            Role = "Technician",
                            Specialty = "General"
                        },
                        new
                        {
                            Id = "TK-06",
                            EmployeeNo = "10740",
                            FailedAttempts = 0,
                            IsActive = true,
                            MaxOpenOrders = 4,
                            Name = "Selin Öztürk",
                            PinHash = "",
                            PinSalt = "",
                            Region = "Akdeniz",
                            Role = "Engineer",
                            Specialty = "Sampling"
                        });
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.WorkOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<double>("Priority")
                        .HasColumnType("REAL");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnicianId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransformerId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Seq")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("TransformerId");

                    b.ToTable("work_orders", (string)null);
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Notification", b =>
                {
                    b.HasOne("TransformerAI.Maintenance.Api.Models.Technician", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransformerAI.Maintenance.Api.Models.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Session", b =>
                {
                    b.HasOne("TransformerAI.Maintenance.Api.Models.Technician", "Technician")
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("TransformerAI.Maintenance.Api.Models.Technician", "Technician")
                        .WithMany("WorkOrders")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("TransformerAI.Maintenance.Api.Models.Technician", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
